# Generated by Django 3.0.11 on 2020-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_sendcloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCloudSenderAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sendcloud ID')),
                ('default_address', models.BooleanField(default=False, verbose_name='Default address')),
                ('company_name', models.CharField(default='', max_length=255, verbose_name='Company Name')),
                ('contact_name', models.CharField(default='', max_length=255, verbose_name='Contact Name')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Main E-Mail address')),
                ('telephone', models.CharField(default='', max_length=255, verbose_name='Phone number')),
                ('street', models.CharField(default='', max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(default='', max_length=100, verbose_name='House number')),
                ('postal_box', models.CharField(default='', max_length=255, verbose_name='Postal box')),
                ('city', models.CharField(default='', max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(default='', max_length=15, verbose_name='Postal Code')),
                ('country', models.CharField(default='', max_length=255, verbose_name='Country code')),
                ('vat_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='VAT number')),
                ('coc_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='COC number')),
                ('eori_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='EORI number')),
            ],
        ),
    ]
